export const SET_SEARCHED_PERSONS = 'SET_SEARCHED_PERSONS';
export const INCREMENT = 'INCREMENT';
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';
export const SET_TAB = 'SET_TAB';
